version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disciplelink-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: disciplelink-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: disciplelink-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: disciplelink
      POSTGRES_USER: discipleuser
      POSTGRES_PASSWORD: disciplepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: disciplelink-mailhog
    ports:
      - "8025:8025"

volumes:
  pgdata:
